name: "Sign"
description: "Sign zowe artifacts"
inputs:
  promote-json-file-name-full:
    description: the promote spec json file name
    required: true
  release-version:
    description: zowe release version
    required: true
  key-id:
    description: gpg key id
    required: true
  private-key-path:
    description: location of the private key
    required: true
  private-key-passphrase:
    description: the passphrase of the private key
    required: true

outputs:
  SIGN_JSON_FILE_NAME_FULL:
    description: the name of the file containing the signed artifacts upload spec
  

runs:
  using: 'node20'
  main: 'dist/index.js'