name: "Promote"
description: "Promote zowe artifacts (copying)"
inputs:
  promote-json-file-name-full:
    description: the promote spec json file name
    required: true
  release-version:
    description: zowe release version
    required: true

outputs:
  RELEASE_ARTIFACTS_DOWNLOAD_SPEC_FILE:
    description: release artifacts download spec file name
  
runs:
  using: 'node20'
  main: 'dist/index.js'