name: "Validate"
description: "Validate zowe artifacts"
inputs:
  build-name:
    description: build-name
    required: true
  build-num:
    description: build-number
    required: true
  release-version:
    description: zowe release version
    required: true
outputs:
  PROMOTE_JSON_FILE_NAME_FULL:
    description: the full file path to be used in promote step
  
runs:
  using: 'node12'
  main: 'dist/index.js'