name: "Message"
description: "Craft a message to show which artifacts are"
inputs:
  release-artifact-download-file:
    description: release artifact download json file full path
    required: true
  release-version:
    description: zowe release version
    required: true
  build-num:
    description: zowe build number
    required: true
outputs:
  slack-message:
    description: the message to put into slack
  
runs:
  using: 'node20'
  main: 'dist/index.js'