#this action will is used for app-server release
name: zlux-git-release
on:
  pull_request:
    types: [opened, reopened, synchronize]
    
  workflow_dispatch:
    inputs: 
      RELEASE_VERSION:
        description: 'Version of release (vX.X.X)'
        required: false
      CREATE_RELEASE:
        type: boolean
        description: 'Create github release'
        required: false
        default: false
      MERGE_TO_MASTER:
        type: boolean
        description: 'Merge rc branches to master'
        required: false
        default: false
      UPDATE_RC:
        type: boolean
        description: 'Merge staging branches to rc'
        required: false
        default: false
      ZOWE_COMMON_C_HEAD:
        description: ''
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'zlux workflow'
        uses: zowe-actions/zlux-builds/git-release@v2.x/main
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN}}
          github-user: ${{ secrets.ZOWE_ROBOT_USER }}
          github-password: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          github-email: ${{ secrets.ZOWE_ROBOT_EMAIL }}
          release-version: ${{ github.event.inputs.RELEASE_VERSION }}
          create-release: ${{ github.event.inputs.CREATE_RELEASE }}
          merge-to-master: ${{ github.event.inputs.MERGE_TO_MASTER }}
          update-rc: ${{ github.event.inputs.UPDATE_RC }}
          zowe-common-c-head: ${{ github.event.inputs.ZOWE_COMMON_C_HEAD }}
