name: Zowe Nightly Pipeline
on:
  workflow_dispatch:

jobs:
  call-build-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 'Call build workflow'
        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          owner: zowe
          repo: zowe-install-packaging
          workflow-filename: build-packaging.yml
          branch-name: users/tom/repository-dispatch
          poll-frequency: 3
          inputs-json-string: '{"BUILD_SMPE":"true","BUILD_DOCKER":"true","BUILD_KUBERNETES":"true"}'
        # env:
        #   DEBUG: 'workflow-remote-call-wait'


  # call-test-workflow:
  #   # needs: call-build-workflow
  #   uses: zowe/zowe-install-packaging/.github/workflows/cicd-test.yml@staging
  #   with: 
  #     NIGHTLY: true
  #     test-file-server: basic/install.ts(zzow02,zzow03,zzow04);basic/install-ptf.ts(zzow02,zzow03,zzow04);basic/install-docker.ts(zzow04)
  #   secrets:
  #     JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
  #     SSH_HOST: ${{ secrets.SSH_HOST }}
  #     SSH_PORT: ${{ secrets.SSH_PORT }}
  #     SSH_USER: ${{ secrets.SSH_USER }}
  #     SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    # Above secrets exists in the environment, doing secrets here to mitigate a problem of reusable workflows where environment secret can
    #   not be passed in properly
    # More info: https://github.community/t/reusable-workflows-secrets-and-environments/203695/23
    # it was a bit weird to pass in above secrets, hope Github team can improve on this
