name: Zowe Nightly Pipeline
on:
  workflow_dispatch:

jobs:
  call-build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 'Call build workflow'
        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
        id: call-build
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          owner: zowe
          repo: zowe-install-packaging
          workflow-filename: build-packaging.yml
          branch-name: staging
          poll-frequency: 2
          inputs-json-string: '{"BUILD_SMPE":"true","BUILD_DOCKER":"true","BUILD_KUBERNETES":"true"}'
        # env:
        #   DEBUG: 'workflow-remote-call-wait'

      - name: 'Report build failure if applied'
        if: ${{ steps.call-build.outputs.workflow-run-conclusion }} != "success"
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Build workflow ${{ steps.call-build.outputs.workflow-run-num }} is not successful')
    outputs:
      build-run-num: ${{ steps.call-build.outputs.workflow-run-num }}
    
      
  call-test-pipeline:
    runs-on: ubuntu-latest
    needs: call-build-pipeline
    steps:
      - name: 'Call test workflow'
        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
        id: call-test
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          owner: zowe
          repo: zowe-install-packaging
          workflow-filename: cicd-test.yml
          branch-name: staging
          poll-frequency: 3
          inputs-json-string: '{"custom-zowe-artifactory-pattern-or-build-number":"${{ needs.call-build-pipeline.outputs.build-run-num }}"}'

      - name: 'Report test failure if applied'
        if: ${{ steps.call-test.outputs.workflow-run-conclusion }} != "success"
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Test workflow ${{ steps.call-test.outputs.workflow-run-num }} is not successful')
        # env:
        #   DEBUG: 'workflow-remote-call-wait'