name: Test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'aaa'
        run: |
          publish_commands="echo \"${{ secrets.DOCKERHUB_PASSWORD }}\" | docker login -u \"${{ secrets.DOCKERHUB_USER }}\" --password-stdin;"
          publish_commands+="pwd"
          eval "$publish_commands"