name: Test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'aaa'
        run: |
          publish_commands="docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }} \n"
          publish_commands+="pwd"
          eval "$publish_commands"